auth
AnnBezv1997/Scooter-store pull request #14
Opened 2021-03-17 22:22 UTC by AnnBezv1997

@marakogr

2021-03-18 06:46 UTC, marakogr requested changes
пара коментов надо поправить, в целом все ок

2021-03-18 06:46 UTC, marakogr commented on Gateway/src/main/java/com/ncedu/scooter/gateway/service/UserService.java
> +            }
а дальше проверка на null есть? может лучше бросать какой нибудь эксепшн? типа если не найдет - UserNotFound
если пароли - соответствующая ошибка

2021-03-18 06:46 UTC, marakogr commented on Gateway/src/main/resources/application.properties
> +#���� ����������� � �������� ������
это гит так отображает символы?)

2021-03-18 06:46 UTC, marakogr commented on ProductInfo/pom.xml
> +			<version>2.9.2</version>
эту версию можно вынести в проперти:
`<properties>
<swagger.version>2.9.2</swagger.version>
</properties>`
а потом использовать так:
`<version>${swagger.version}</version>`

2021-03-25 10:03 UTC, AnnBezv1997 commented
@marakogr привет, добавила
У меня такой вопрос возник, а нужно чтобы микросервис, где фронт ScooterClient был клиентом еврики?

2021-03-25 15:12 UTC, merged